# frozen_string_literal: true

AllCops:
  Enabled: false

  Exclude:
    - 'test/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'vendor/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'log/**/*'

Style/Documentation:
  Enabled: false
